<?php

/**
 * GEMS Custom Functions
 */
function gems_footer_social_media($type) {
	$form["fieldset_{$type}"] = array(
		"#type" => "fieldset",
		"#title" => t(ucwords("{$type}")),
		"#collapsible" => TRUE,
		"#collapsed" => TRUE
	);

	$form["fieldset_{$type}"]["{$type}_textfield"] = array(
		"#type" => "textfield",
		"#title" => t(ucwords("{$type} link")),
		"#default_value" => variable_get("{$type}_textfield", ""),
		"#description" => "Link to your {$type} account",
		"#size" => 31
	);

	$form["fieldset_{$type}"]["{$type}_imagefield"] = array(
		"#type" => "managed_file",
		"#title" => t(ucwords("{$type} image")),
		"#default_value" => variable_get("{$type}_imagefield_fid", ""),
		"#description" => "Select an image. Only *.png image is allowed.",
		"#upload_location" => "public://block_image/",
		"#upload_validators" => array(
			'file_validate_extensions' => array('png'),
		)
	);

	return $form;
}

function gems_module_block_save($delta = "", $edit = array()) {
	switch ($delta) {
		case 'footer_content':
			// Save textfield
			variable_set("facebook_textfield", $edit["facebook_textfield"]);
			variable_set("twitter_textfield", $edit["twitter_textfield"]);
			variable_set("google_textfield", $edit["google_textfield"]);
			//variable_set("vimeo_textfield", $edit["vimeo_textfield"]);
			//variable_set("linkedin_textfield", $edit["linkedin_textfield"]);

      // Saving the file
			gems_module_social_media_upload_block_save("facebook", $edit["facebook_imagefield"], $delta);
			gems_module_social_media_upload_block_save("twitter", $edit["twitter_imagefield"], $delta);
			gems_module_social_media_upload_block_save("google", $edit["google_imagefield"], $delta);
			//gems_module_social_media_upload_block_save("vimeo", $edit["vimeo_imagefield"], $delta);
			//gems_module_social_media_upload_block_save("linkedin", $edit["linkedin_imagefield"], $delta);
		break;
	}
}

function gems_module_get_image($fid) {
	$image = file_load(variable_get($fid));
	return '<img src="'. file_create_url($image->uri) .'" class="icons" width="20" />';
}

function gems_module_footer_content_block_view() {
	$html =
		'<div class="social-media-icons small-12 medium-5 large-5 medium-centered large-centered column">
			<a href="'. variable_get('facebook_textfield').'"> '.gems_module_get_image('facebook_imagefield_fid') .' </a>
			<a href="'. variable_get('twitter_textfield').'"> '.gems_module_get_image('twitter_imagefield_fid') .' </a>
			<a href="'. variable_get('google_textfield').'"> '.gems_module_get_image('google_imagefield_fid') .' </a>	
		</div>'
		. '<div class="dev-by small-12 medium-6 large-6 column">Designed & Developed by <a href="http://globaledge-media.com" target="_blank">GlobalEdge Media Solutions</a></div>'
		. '<div class="rights-reserved small-12 medium-6 large-6 column">All Rights Reserved. Copyright Louie\'s Dental 2015</div>';

	return $html;
}

/**
 * Implements hook_init().
 *
 * function gems_module_init() {
 *   if (arg(0) == "node" && arg(1) == "add" && arg(2) == "page") {
 *     drupal_add_js(drupal_get_path('theme', 'gems').'/js/index.js',  array('scope' => 'footer'));
 *   }
 * }
 */

/**
 * Implements hook_block_info().
 */
function gems_module_block_info() {
	$blocks = array();

	$blocks['footer_content'] = array(
		'info' => t('Footer Content')
	);
	return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function gems_module_block_configure($delta = "") {
	$form = array();

	switch ($delta) {
		case 'footer_content':
			array_push($form, gems_footer_social_media("facebook"));
			array_push($form, gems_footer_social_media("twitter"));
			array_push($form, gems_footer_social_media("google"));
			//array_push($form, gems_footer_social_media("vimeo"));
			//array_push($form, gems_footer_social_media("linkedin"));
		break;
	}

	return $form;
}

/**
 * Implements hook_block_save().
 */

function gems_module_social_media_upload_block_save($social, $type, $delta) {
	$file = file_load($type);
	$file->status = FILE_STATUS_PERMANENT;
	file_save($file);
	$block = block_load('gems_module', $delta);
	file_usage_add($file, 'gems_module', 'block', $block->bid);
	variable_set("{$social}_imagefield_fid", $file->fid);
}

/**
 * Implements hook_block_view().
 */
function gems_module_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'footer_content':
      $block['content'] = gems_module_footer_content_block_view();
      break;
  }
  return $block;
}