<?php
/**
 * Desc
 */
function modulenable_update_7000() {
  $module = array('ctools');
  
  module_enable($module);
}


function modulenable_update_7001() {
  $module = array('views');

  module_enable($module);
}


function modulenable_update_7002() {
  $module = array('views_ui');

  module_enable($module);
}


function modulenable_update_7003() {
  $module = array('pathauto');

  module_enable($module);
}

