<?php

/**
 * Defines CBR.ru as currency exchange rate sync provider.
 *
 * @return array
 *   An array of information about the callback.
 *   The array contains a sub-array for each callback, with a machine name
 *   as the key.
 */
function commerce_multicurrency_rub_commerce_multicurrency_exchange_rate_sync_provider_info() {
  return array(
    'cbr' => array(
      'title' => t('Central Bank of the Russian Federation'),
      'callback' => 'commerce_multicurrency_rub_exchange_rate_sync_provider_cbr',
      'file' => drupal_get_path('module', 'commerce_multicurrency_rub') . '/commerce_multicurrency_rub.cbr.inc',
    ),
  );
}